### ISSUE TITLE
Dropdown icon with FontAwesome

### ISSUE THREAD

**Issue by sabas** [GavickPro/Meet-Gavern#171]
In template.css

``` css
.haschild:after {
content: "\f101";
font-family: FontAwesome;
font-style: normal;
font-weight: normal;
text-decoration: inherit;
color: #000;
display: inline-block;
width: 0.75em;
text-align: right;
}

.haschild:hover:after {
content: "\f103";
font-family: FontAwesome;
font-style: normal;
font-weight: normal;
text-decoration: inherit;
color: #000;
display: inline-block;
width: 0.75em;
text-align: right;
}
```

If you update Fontawesome to last version the same behaviour could be added with class fa-fw and icons
fa-angle-double-right
fa-angle-double-down
