### ISSUE TITLE
Aside problem

### ISSUE THREAD

**Issue by dziudek** [GavickPro/Meet-Gavern#42]
@bkrztuk - please look at this problem - even if the aside doesn't exist the space at left is available. We need to recode it to use:

``` css
aside + CONTENT_CONTAINER {
margin-left: X;
}
```

To avoid this situation.
